### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by nicolasbogo** [pawp81/AdminSubmissionsAPI#2]
After launching the command I encountered this error :

Error submitting URL: 
{ "error": { "code": "ActivityLimitReached", "message": "The client application has been throttled for reaching an activity limit. The request may be repeated after a delay, the length of which may be specified in a 'Retry-After' 
header.", "innerError": { "request-id": "14723a9d-4f0e-44d1-92dc-d9dabde08933", "date": "2020-04-23T09:04:49" } } }

**Comment by pawp81** [comment]
Throttling can happen if you submit the same URL in couple of minutes or if too many URLs were submitted in short timeframe. How many URL have you submitted?

**Comment by nicolasbogo** [comment]
I've just submited 1 mail

**Comment by pawp81** [comment]
I suppose you meant one URL? Please try again in 1h and if you get the same error paste it hear please.

**Comment by nicolasbogo** [comment]
No, I mean a MSG file. It's not supported to send a MSG file ?

**Comment by pawp81** [comment]
This script can only submit URLs. Not entire messages.

**Comment by nicolasbogo** [comment]
Oh... Do you plan to submit messages and also have a feedbacks for the system ?

**Comment by pawp81** [comment]
You can submit messages as well using API (or GUI) but not using this script. You can write your own script to do so :-)

**Comment by nicolasbogo** [comment]
Could you give me some links to have the knowledge of the API ?

**Comment by pawp81** [comment]
https://docs.microsoft.com/en-us/graph/api/resources/threatassessment-api-overview
